In [34]:
import pandas as pd
import re
from nltk.corpus import stopwords

In [35]:
data = pd.read_csv("C:/Users/sinch/Downloads/DS_Projects/resumes.csv", encoding = 'ISO-8859-1' )
data

,resume_id,resume_text,experience_years
0,R1,deep learning tensorflow keras python,1
1,R2,sas clinical sdtm adam tlf cdisc,3
2,R3,sql excel powerbi data analysis reporting,3
3,R4,python pandas numpy machine learning sql stati...,1
4,R5,deep learning tensorflow keras python,1
...,...,...,...
295,R296,deep learning tensorflow keras python,0
296,R297,sas clinical sdtm adam tlf cdisc,0
297,R298,python pandas numpy machine learning sql stati...,0
298,R299,sql excel powerbi data analysis reporting,3
299,R300,python pandas numpy machine learning sql stati...,1

In [36]:
df = pd.read_csv("C:/Users/sinch/Downloads/DS_Projects/job_descriptions.csv" )
df

  job_id                 job_role                     job_description
0     J1             Data Analyst     sql excel powerbi data analysis
1     J2           Data Scientist  python machine learning statistics
2     J3  Clinical SAS Programmer          sas clinical sdtm adam tlf

In [44]:
stop_words = set(stopwords.words('english'))

def clean_text(text):
    text = str(text).lower()   # lowercase
    text = re.sub(r'[^a-zA-Z]', ' ', text)  # remove symbols
    
    words = text.split()
    words = [w for w in words if w not in stop_words]
    
    return " ".join(words)
print(stop_words)

{'we', 'isn', 'herself', 'ma', "won't", 'above', 're', 'down', 'yourself', "i'm", 'such', 'because', "you'd", 'his', 'did', 'here', 'hers', 'at', 'how', 'those', 'its', 'has', 'needn', 'does', 've', 'these', 'hasn', 'been', 'am', 'itself', 'why', "it'll", "wasn't", 'don', "it's", 'off', "isn't", 'or', 'do', 'is', 'below', 'her', 'weren', 'wasn', 'all', "you've", 'me', 'o', "should've", 'they', 'themselves', 'couldn', 'be', 'again', 'i', "needn't", 'won', 'for', "i'll", 'wouldn', 'my', 'very', 'whom', "you're", 'shan', "don't", "mustn't", "they're", "hasn't", 'of', 'haven', 'she', 'myself', "he's", "it'd", 'ourselves', 'that', 'not', 'yourselves', 'where', 'by', 'to', 'being', 'can', "doesn't", 'have', 'more', "they'll", "they've", "they'd", "you'll", 'their', 'both', "didn't", 'any', 'no', "shouldn't", 'only', 'before', 'now', 'through', 'some', 'shouldn', "we'd", "she'll", 'on', 'most', 'them', 'during', 'which', 'and', 'having', "she'd", 'your', 'further', 'too', "aren't", 'few', 'were', 'it', 'so', 'once', 'there', 'than', 'had', 'own', "i'd", 'same', 'mustn', 'just', 'was', "weren't", "that'll", 'aren', 'about', 'y', 'he', 'the', 'what', 'this', "mightn't", 'himself', 'nor', "we'll", 'will', 'other', 'you', 'll', 'then', 'mightn', 'into', "haven't", "shan't", 'are', 'yours', 'ours', 'who', "she's", "we've", "we're", 'an', "wouldn't", 'out', "he'll", 'ain', 'doing', "i've", 'over', 'if', 'as', 'with', 'but', 't', 'd', 'after', 's', "couldn't", 'should', 'hadn', 'up', 'under', 'a', 'theirs', 'from', 'between', 'while', "hadn't", 'our', 'against', 'when', 'him', 'each', 'didn', 'until', 'm', 'in', "he'd", 'doesn'}

In [45]:
data['clean_resume'] = data['resume_text'].apply(clean_text)

data[['resume_text', 'clean_resume']].head()

,resume_text,clean_resume
0,deep learning tensorflow keras python,deep learning tensorflow keras python
1,sas clinical sdtm adam tlf cdisc,sas clinical sdtm adam tlf cdisc
2,sql excel powerbi data analysis reporting,sql excel powerbi data analysis reporting
3,python pandas numpy machine learning sql stati...,python pandas numpy machine learning sql stati...
4,deep learning tensorflow keras python,deep learning tensorflow keras python

In [50]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()

X = vectorizer.fit_transform(data['clean_resume'])
X

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1804 stored elements and shape (300, 21)>

In [53]:
from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity(X)
X

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1804 stored elements and shape (300, 21)>

In [54]:
X.toarray()

array([[0.        , 0.        , 0.        , ..., 0.        , 0.50096413,
        0.        ],
       [0.40824829, 0.        , 0.40824829, ..., 0.        , 0.        ,
        0.40824829],
       [0.        , 0.42710605, 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.42378379, 0.        ,
        0.        ],
       [0.        , 0.42710605, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.42378379, 0.        ,
        0.        ]])